name: docker

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # step for main/latest (docker only)
      - name: Build and push latest docker image
        if: success() && github.ref == 'refs/heads/main'
        run: |
          docker build . -t ghcr.io/minetest-go/go-cicd-template:latest
          docker push ghcr.io/minetest-go/go-cicd-template:latest